language: java

node_js:
  - 0.10

jdk: oraclejdk7

# whitelist
branches:
  only:
    - travis

env:
  matrix:
    # see set_up_new_machine.sh
    
before_install:
  # Download and configure android among other deps
  - ./scripts/set_up_new_machine.sh
 
before_script:
  # Make sure the emulator has started before running tests
  - ./scripts/wait_for_emulator.sh

script: grunt everything
